security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: false
            form_login:
                login_path: login
                default_target_path: training
                username_parameter: username
                password_parameter: password
                use_forward: false 
                enable_csrf: true   
            logout:
                path: logout
                target: training
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/check-username, roles: PUBLIC_ACCESS }
        - { path: ^/google, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/training, roles: PUBLIC_ACCESS }
        - { path: ^/profile, roles: PUBLIC_ACCESS }
        - { path: ^/rating, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }